We Apologize For The Inconvenience.
<?php echo $TEXT_BREAK; ?>
<?php echo $TEXT_BREAK; ?>
It appears that you may be having problems logging into Nomsterz.com.
<?php echo $TEXT_BREAK; ?>
<?php echo $TEXT_BREAK; ?>
We detected multiple attempts to login to our site using this email address. If this was you, we advise that you use our Forgotten Login Form at [<?php echo $RESET_PWD_LINK; ?>] to reset your password.
<?php echo $TEXT_BREAK; ?>
<?php echo $TEXT_BREAK; ?>
If this was not you, please still use the Forgotten Login Form, but also contact us at customerservice@Nomsterz.com so we can make sure your account is properly secured.
<?php echo $TEXT_BREAK; ?>
<?php echo $TEXT_BREAK; ?>
<?php echo $TEXT_BREAK; ?>
To ensure delivery of this and future emails, please add welcome@notarytools.net to your Address Book or Safe List. <?php echo $TEXT_BREAK; ?>
<?php echo $TEXT_BREAK; ?>
Your email address and contact information will not be shared with any third parties without your permission, unless we are required to do so by law or we need to perform necessary site functions.  <?php echo $TEXT_BREAK; ?>
<?php echo $TEXT_BREAK; ?>
<?php echo $TEXT_BREAK; ?>
Sincerely, <?php echo $TEXT_BREAK; ?>

The Nomsterz Team
<?php echo $TEXT_BREAK; ?>
<?php echo $CUSTOMER_SERVICE_NUMBER; ?>
<?php echo $TEXT_BREAK; ?>
<?php echo $TEXT_BREAK; ?>

P.S.: We are truly sorry that you are having issues with our site. We will do all that is possible to get you back up and running. Thank you for your business.
<?php echo $TEXT_BREAK; ?>
<?php echo $TEXT_BREAK; ?>

Twitter Page: <?php echo $TWT_LINK; ?>
<?php echo $TEXT_BREAK; ?>
Facebook Page: <?php echo $FB_LINK; ?>
<?php echo $TEXT_BREAK; ?>
<?php echo $TEXT_BREAK; ?>

Copyright &copy; <?php echo $CURR_YR; ?> Nomsterz, All rights reserved.<?php echo $TEXT_BREAK; ?>
