We All Forget Sometimes.
<?php echo $TEXT_BREAK; ?>
We are Here to Help.
<?php echo $TEXT_BREAK; ?>
<?php echo $TEXT_BREAK; ?>
<?php echo $FULL_NAME; ?>,
<?php echo $TEXT_BREAK; ?>
<?php echo $TEXT_BREAK; ?>
It appears that you may need to change your password to access your Nomsterz.com account.
<?php echo $TEXT_BREAK; ?>
<?php echo $TEXT_BREAK; ?>
Well, we can make that happen. If this was not you however, we advise that you DO NOT click this link and instead contact us at customerservice@nomsterz.com so we can make sure your account is properly setup and secured.
<?php echo $TEXT_BREAK; ?>
If this is actually your decision, please, click, copy or paste this url in your browser address bar to re-verify Your Email Address:
<?php echo $TEXT_BREAK; ?>
<?php echo $TEXT_BREAK; ?>
<?php echo $VRFY_EML_LINK; ?>
<?php echo $TEXT_BREAK; ?>
<?php echo $TEXT_BREAK; ?>
Follow the instructions on the page you bring up.
<?php echo $TEXT_BREAK; ?>
<?php echo $TEXT_BREAK; ?>
To ensure delivery of this and future emails, please add welcome@notarytools.net to your Address Book or Safe List. <?php echo $TEXT_BREAK; ?>
<?php echo $TEXT_BREAK; ?>
Your email address and contact information will not be shared with any third parties without your permission, unless we are required to do so by law or we need to perform necessary site functions.  <?php echo $TEXT_BREAK; ?>
<?php echo $TEXT_BREAK; ?>
<?php echo $TEXT_BREAK; ?>
Sincerely, <?php echo $TEXT_BREAK; ?>

The Nomsterz Team
<?php echo $TEXT_BREAK; ?>
<?php echo $CUSTOMER_SERVICE_NUMBER; ?>
<?php echo $TEXT_BREAK; ?>
<?php echo $TEXT_BREAK; ?>

P.S.: We are truly sorry that you are having issues with our site. We will do all that is possible to get you up and running. Thank you for your business.
<?php echo $TEXT_BREAK; ?>
<?php echo $TEXT_BREAK; ?>

Twitter Page: <?php echo $TWT_LINK; ?>
<?php echo $TEXT_BREAK; ?>
Facebook Page: <?php echo $FB_LINK; ?>
<?php echo $TEXT_BREAK; ?>
<?php echo $TEXT_BREAK; ?>

Copyright &copy; <?php echo $CURR_YR; ?> Nomsterz, All rights reserved.<?php echo $TEXT_BREAK; ?>
