This is a Notice.
<?php echo $TEXT_BREAK; ?>
Your Profile's Information has been Changed.
<?php echo $TEXT_BREAK; ?>
<?php echo $TEXT_BREAK; ?>
<?php echo $FULL_NAME; ?>,
<?php echo $TEXT_BREAK; ?>
<?php echo $TEXT_BREAK; ?>
Changes have been recently applied to your profile. If this was not you, we advise that you contact us at customerservice@nomsterz.com so we can make sure your account is properly setup and secured.
<?php echo $TEXT_BREAK; ?>
<?php echo $TEXT_BREAK; ?>
<?php echo $TEXT_BREAK; ?>
To ensure delivery of this and future emails, please add welcome@notarytools.net to your Address Book or Safe List. <?php echo $TEXT_BREAK; ?>
<?php echo $TEXT_BREAK; ?>
Your email address and contact information will not be shared with any third parties without your permission, unless we are required to do so by law or we need to perform necessary site functions.  <?php echo $TEXT_BREAK; ?>
<?php echo $TEXT_BREAK; ?>
<?php echo $TEXT_BREAK; ?>
Sincerely,
<?php echo $TEXT_BREAK; ?>
The Nomsterz Team
<?php echo $TEXT_BREAK; ?>
<?php echo $CUSTOMER_SERVICE_NUMBER; ?>
<?php echo $TEXT_BREAK; ?>
<?php echo $TEXT_BREAK; ?>
<?php echo $TEXT_BREAK; ?>

Twitter Page: <?php echo $TWT_LINK; ?>
<?php echo $TEXT_BREAK; ?>
Facebook Page: <?php echo $FB_LINK; ?>
<?php echo $TEXT_BREAK; ?>
<?php echo $TEXT_BREAK; ?>

Copyright &copy; <?php echo $CURR_YR; ?> Nomsterz, All rights reserved.<?php echo $TEXT_BREAK; ?>
