<div class="container">
	<div class="row">
		<div id="content" class="col-lg-12">





			<!-- PAGE HEADER-->
			<div class="row">
				<div class="col-sm-12">
					<div class="page-header">
						<!-- STYLER -->

						<!-- /STYLER -->





						<div class="clearfix">
							<h3 class="content-title pull-left">Start Here, <a href="<?php echo $this->notaryProfileLink; ?>"><?php echo $this->notaryFirstName; ?></a></h3>


							<!-- DATE RANGE PICKER -->
							<span class="date-range pull-right hidden-xs  hidden-sm">
								<div class="btn-group">
									<a class="js_update btn btn-default hidden-xs" href="#">Date Range: </a>

									<a id="reportrange" class="btn reportrange">
										<i class="fa fa-calendar"></i>
										<span></span>
										<i class="fa fa-angle-down"></i>
									</a>
								</div>
							</span>
							<!-- /DATE RANGE PICKER -->




						</div>
						<div class="description">Choose a section you would like to begin with or use our Search Feature.</div>
					</div>
				</div>
			</div>
			<!-- /PAGE HEADER -->



			<!-- First Row CONTENT -->
			<div class="row">
				<!-- COLUMN 1 -->
				<div class="col-lg-6">
					<div class="jumbotron">
						<h1>Signings</h1>
						<p>Quickly add, view &amp; edit signing orders. Add complete or partial details. Create tasks to remind you of planned work.</p>
						<p>
							<a href="/NotarySignings" class="btn btn-primary btn-icon input-block-level btn-lg" role="button">
								<span class="visible-xs"><i class="fa fa-paperclip fa-fw"></i> <?php echo $this->signingsSectionButtonText_xs; ?></span>
								<span class="visible-sm"><i class="fa fa-paperclip fa-fw"></i> <?php echo $this->signingsSectionButtonText_sm; ?></span>
								<span class="visible-md"><i class="fa fa-paperclip fa-fw"></i> <?php echo $this->signingsSectionButtonText_md; ?></span>
								<span class="visible-lg"><i class="fa fa-paperclip fa-fw"></i> <?php echo $this->signingsSectionButtonText_lg; ?></span>
							</a>
						</p>
					</div>
				</div>
				<!-- /COLUMN 1 -->

				<!-- COLUMN 2 -->
				<div class="col-md-6">
					<div class="jumbotron">
						<h1>The Business</h1>
						<p>Visually analyze all aspects of your loan signing business. Store, track and measure individual data points. </p>
						<p>
							<a href="/NotaryBusiness" class="btn btn-primary btn-icon input-block-level btn-lg" role="button">
								<span class="visible-xs"><i class="fa fa-money fa-fw"></i> <?php echo $this->businessSectionButtonText_xs; ?></span>
								<span class="visible-sm"><i class="fa fa-money fa-fw"></i> <?php echo $this->businessSectionButtonText_sm; ?></span>
								<span class="visible-md"><i class="fa fa-money fa-fw"></i> <?php echo $this->businessSectionButtonText_md; ?></span>
								<span class="visible-lg"><i class="fa fa-money fa-fw"></i> <?php echo $this->businessSectionButtonText_lg; ?></span>
							</a>
						</p>
					</div>
				</div>
				<!-- /COLUMN 2 -->
			</div>
		   <!-- /First Row CONTENT -->



			<!-- Second Row CONTENT -->
			<div class="row">
				<!-- COLUMN 1 -->
				<div class="col-md-6">
					<div class="jumbotron">
						<h1>Website</h1>
						<p>Choose your site domain and enable a website layout in minutes. View web traffic statistics. Add social features.</p>
						<p>
							<a href="/NotaryWebsite" class="btn btn-primary btn-icon input-block-level btn-lg" role="button">
								<span class="visible-xs"><i class="fa fa-laptop fa-fw"></i> <?php echo $this->websiteSectionButtonText_xs; ?></span>
								<span class="visible-sm"><i class="fa fa-laptop fa-fw"></i> <?php echo $this->websiteSectionButtonText_sm; ?></span>
								<span class="visible-md"><i class="fa fa-laptop fa-fw"></i> <?php echo $this->websiteSectionButtonText_md; ?></span>
								<span class="visible-lg"><i class="fa fa-laptop fa-fw"></i> <?php echo $this->websiteSectionButtonText_lg; ?></span>
							</a>
						</p>
					</div>
				</div>
				<!-- /COLUMN 1 -->

				<!-- COLUMN 2 -->
				<div class="col-md-6">
					<div class="jumbotron">
						<h1>The Numbers</h1>
						<p>Your personal number cruncher! Find answers to industry standard questions. Compare member averages to your business performance.</p>
						<a href="/NotaryNumbers" class="btn btn-primary btn-icon input-block-level btn-lg" role="button">
							<span class="visible-xs"><i class="fa fa-bar-chart-o fa-fw"></i> <?php echo $this->dataSectionButtonText_xs; ?></span>
							<span class="visible-sm"><i class="fa fa-bar-chart-o fa-fw"></i> <?php echo $this->dataSectionButtonText_sm; ?></span>
							<span class="visible-md"><i class="fa fa-bar-chart-o fa-fw"></i> <?php echo $this->dataSectionButtonText_md; ?></span>
							<span class="visible-lg"><i class="fa fa-bar-chart-o fa-fw"></i> <?php echo $this->dataSectionButtonText_lg; ?></span>
						</a>
					</div>
				</div>
				<!-- /COLUMN 2 -->
			</div>
		   <!-- /Second Row CONTENT -->



			<!-- Third Row CONTENT -->
			<div class="row">
				<!-- COLUMN 1 -->
				<div class="col-md-6">
					<div class="jumbotron">
						<h1>Document Center</h1>
						<p>Generate reports. Schedule data backups.</p>
						<a href="/NotaryDocuments" class="btn btn-primary btn-icon input-block-level btn-lg" role="button">
							<span class="visible-xs"><i class="fa fa-folder-open fa-fw"></i> <?php echo $this->documentSectionButtonText_xs; ?></span>
							<span class="visible-sm"><i class="fa fa-folder-open fa-fw"></i> <?php echo $this->documentSectionButtonText_sm; ?></span>
							<span class="visible-md"><i class="fa fa-folder-open fa-fw"></i> <?php echo $this->documentSectionButtonText_md; ?></span>
							<span class="visible-lg"><i class="fa fa-folder-open fa-fw"></i> <?php echo $this->documentSectionButtonText_lg; ?></span>
						</a>
					</div>
				</div>
				<!-- /COLUMN 1 -->

				<!-- COLUMN 2 -->
				<div class="col-md-6">
					<div class="jumbotron">
						<h1>Resources</h1>
						<p>Easily manage all your resources. Track expenses.</p>
						<a href="/NotaryResources" class="btn btn-primary btn-icon input-block-level btn-lg" role="button">
							<span class="visible-xs"><i class="fa fa-th-large fa-fw"></i> <?php echo $this->resourceSectionButtonText_xs; ?></span>
							<span class="visible-sm"><i class="fa fa-th-large fa-fw"></i> <?php echo $this->resourceSectionButtonText_sm; ?></span>
							<span class="visible-md"><i class="fa fa-th-large fa-fw"></i> <?php echo $this->resourceSectionButtonText_md; ?></span>
							<span class="visible-lg"><i class="fa fa-th-large fa-fw"></i> <?php echo $this->resourceSectionButtonText_lg; ?></span>
						</a>
					</div>
				</div>
				<!-- /COLUMN 2 -->
			</div>
		   <!-- /Third Row CONTENT -->



			<!-- Fourth Row CONTENT -->
			<div class="row">
				<!-- COLUMN 1 -->
				<div class="col-md-6">
					<div class="jumbotron">
						<h1>Help & Settings</h1>
						<p>Get answers. Save Settings. Contact support.</p>
						<a href="/NotaryHelp" class="btn btn-primary btn-icon input-block-level btn-lg" role="button">
							<span class="visible-xs"><i class="fa fa-question-circle fa-fw"></i> <?php echo $this->helpSectionButtonText_xs; ?></span>
							<span class="visible-sm"><i class="fa fa-question-circle fa-fw"></i> <?php echo $this->helpSectionButtonText_sm; ?></span>
							<span class="visible-md"><i class="fa fa-question-circle fa-fw"></i> <?php echo $this->helpSectionButtonText_md; ?></span>
							<span class="visible-lg"><i class="fa fa-question-circle fa-fw"></i> <?php echo $this->helpSectionButtonText_lg; ?></span>
						</a>
					</div>
				</div>
				</div>
				<!-- /COLUMN 1 -->

				<!-- COLUMN 2 -->
				<div class="col-md-6">

				</div>
				<!-- /COLUMN 2 -->
			</div>
		   <!-- /Fourth Row CONTENT -->


			<div class="footer-tools">
				<span class="go-top">
					<i class="fa fa-chevron-up"></i> Top
				</span>
			</div>
		</div><!-- /CONTENT-->
	</div>
</div>