
<section id="content">

		<div class="container">

			<div class="page-header clearfix">

				<h1>There seems to be a problem...</h1>

			</div><!--/ .page-header-->

			<div class="fifteen columns">

				<div class="e404 clearfix">

					<h1><?php echo $this->Exclamation; ?></h1>
					<h2><p><?php echo $this->ErrorMsg; ?></p></h2>
					<a class="button big default" href="/">Get Me Back to Homepage!</a>

				</div><!--/ .e404-->

			</div><!--/ .columns-->

		</div><!--/ .container-->

	</section><!--/ #content-->