<div class="container">
	<div class="row">
		<div id="content" class="col-lg-12">





			<!-- PAGE HEADER-->
			<div class="row">
				<div class="col-sm-12">
					<div class="page-header">
						<div class="clearfix">
							<h3 class="content-title pull-left">Your Signings, <a href="<?php echo $this->notaryProfileLink; ?>"><?php echo $this->notaryFirstName; ?></a></h3>
						</div>
						<div class="description">Choose a section you would like to begin with or use our Search Feature.</div>
					</div>
				</div>
			</div>
			<!-- /PAGE HEADER -->



			<!-- Section Buttons CONTENT -->
			<div class="row">
				<!-- Page Specific Buttons -->
				<span class="ntzSectionHeadingButtons pull-right">

					<div class="btn-group dropdown" style="margin-bottom:5px">

						<a class="btn btn-primary" href="/NotarySigningOrders" style="padding: 8px;">
							<span class="visible-xs">Orders</span>
							<span class="visible-sm">Orders</span>
							<span class="visible-md">Signing Orders</span>
							<span class="visible-lg">Signing Orders</span>
						</a>
						<button class="btn btn-primary dropdown-toggle" style="padding: 8px;" data-toggle="dropdown">
							<span class="caret"></span>
						</button>
						<ul class="dropdown-menu pull-right">
							<li><a href="#">Action</a></li>
							<li><a href="#">Another action</a></li>
							<li><a href="#">Something else here</a></li>
							<li class="divider"></li>
							<li><a href="#">Separated link</a></li>
						</ul>

					</div>

					<div class="btn-group dropdown" style="margin-bottom:5px">

						<a class="btn btn-primary" href="/NotarySigningSources"  style="padding: 8px;">
							<span class="visible-xs">Sources</span>
							<span class="visible-sm">Sources</span>
							<span class="visible-md">Signing Sources</span>
							<span class="visible-lg">Signing Sources</span>
						</a>
						<button class="btn btn-primary dropdown-toggle" style="padding: 8px;" data-toggle="dropdown">
							<span class="caret"></span>
						</button>
						<ul class="dropdown-menu pull-right">
							<li><a href="#">Action</a></li>
							<li><a href="#">Another action</a></li>
							<li><a href="#">Something else here</a></li>
							<li class="divider"></li>
							<li><a href="#">Separated link</a></li>
						</ul>

					</div>

					<div class="btn-group dropdown" style="margin-bottom:5px">

						<a class="btn btn-primary" href="/NotaryData"  style="padding: 8px;">
							<span class="visible-xs">Data</span>
							<span class="visible-sm">Data</span>
							<span class="visible-md">Data & Reports</span>
							<span class="visible-lg">View Data & Reports</span>
						</a>
						<button class="btn btn-primary dropdown-toggle" style="padding: 8px;" data-toggle="dropdown">
							<span class="caret"></span>
						</button>
						<ul class="dropdown-menu pull-right">
							<li><a href="#">Action</a></li>
							<li><a href="#">Another action</a></li>
							<li><a href="#">Something else here</a></li>
							<li class="divider"></li>
							<li><a href="#">Separated link</a></li>
						</ul>

					</div>

				</span>
				<!-- /Page Specific Buttons -->
			</div>
		   <!-- /Section Buttons CONTENT -->

			<div class="separator"></div>

			<!-- Quick View Items -->
			<div class="row">
				<!-- Quick Stats -->
				<div class="col-md-6">
					<div class="row">
					  	<div class="col-lg-6">
						 	<div class="dashbox panel panel-default">
								<div class="panel-body">
							   		<div class="panel-left red">
										<i class="fa fa-instagram fa-3x"></i>
							   		</div>
							   		<div class="panel-right">
										<div class="number">6718</div>
										<div class="title">Total Signings</div>
										<span class="label label-success">
											26% <i class="fa fa-arrow-up"></i>
										</span>
							   		</div>
								</div>
						 	</div>
					  	</div>
					  	<div class="col-lg-6">
						 	<div class="dashbox panel panel-default">
								<div class="panel-body">
							   		<div class="panel-left red">
										<i class="fa fa-instagram fa-3x"></i>
							   		</div>
							   		<div class="panel-right">
										<div class="number">6718</div>
										<div class="title">Total Mileage</div>
										<span class="label label-success">
											26% <i class="fa fa-arrow-up"></i>
										</span>
							   		</div>
								</div>
						 	</div>
					  	</div>
					</div>
					<div class="row">
					  	<div class="col-lg-6">
						 	<div class="dashbox panel panel-default">
								<div class="panel-body">
							   		<div class="panel-left red">
										<i class="fa fa-instagram fa-3x"></i>
							   		</div>
							   		<div class="panel-right">
										<div class="number">6718</div>
										<div class="title">Paid / Unpaid Signings</div>
										<span class="label label-success">
											26% <i class="fa fa-arrow-up"></i>
										</span>
							   		</div>
								</div>
						 	</div>
					  	</div>
					  	<div class="col-lg-6">
						 	<div class="dashbox panel panel-default">
								<div class="panel-body">
							   		<div class="panel-left red">
										<i class="fa fa-instagram fa-3x"></i>
							   		</div>
							   		<div class="panel-right">
										<div class="number">6718</div>
										<div class="title">Number of Sources</div>
										<span class="label label-success">
											26% <i class="fa fa-arrow-up"></i>
										</span>
							   		</div>
								</div>
						 	</div>
					  	</div>
					</div>
					<div class="separator"></div>
					<div class="row">
						<div class="col-md-12">
							<!-- BOX -->
								<div class="box border blue">
									<div class="box-title">
										<h4><i class="fa fa-bar-chart-o"></i>What's my busiest day?</h4>
										<div class="tools">
											<a href="#box-config" data-toggle="modal" class="config">
												<i class="fa fa-cog"></i>
											</a>
											<a href="javascript:;" class="reload">
												<i class="fa fa-refresh"></i>
											</a>
											<a href="javascript:;" class="collapse">
												<i class="fa fa-chevron-up"></i>
											</a>
										</div>
									</div>
									<div class="box-body">
										<div id="chart_5" class="chart" style="height: 367px;"></div>
									</div>
								</div>
								<!-- /BOX -->
						</div>
				   </div>
				</div>
				<!-- /Quick Stats -->

				<!-- Section CALENDAR -->
				<div class="col-md-6">
					<div class="box border blue">
						<div class="box-title">
							<h4><i class="fa fa-calendar"></i>Calendar</h4>
							<div class="tools">
								<a href="#box-config" data-toggle="modal" class="config">
									<i class="fa fa-cog"></i>
								</a>
								<a href="javascript:;" class="reload">
									<i class="fa fa-refresh"></i>
								</a>
								<a href="javascript:;" class="collapse">
									<i class="fa fa-chevron-up"></i>
								</a>
							</div>
						</div>
						<div class="box-body">
							<div id='calendar'></div>
						</div>
					</div>
				</div>
				<!-- /Section CALENDAR -->
			</div>
			<!-- /Quick View Items -->


					<div class="separator"></div>

			<!-- Signings By Month for Year X -->
			<div class="row">
				<div class="col-md-12">
					<!-- BOX -->
					<div class="box border blue">
						<div class="box-title">
							<h4><i class="fa fa-table"></i>Signings by Month and Year</h4>
							<div class="tools hidden-xs">
								<a href="#box-config" data-toggle="modal" class="config">
									<i class="fa fa-cog"></i>
								</a>
								<a href="javascript:;" class="reload">
									<i class="fa fa-refresh"></i>
								</a>
								<a href="javascript:;" class="collapse">
									<i class="fa fa-chevron-up"></i>
								</a>
							</div>
						</div>

						<div class="box-body">
							<table id="datatable1" cellpadding="0" cellspacing="0" border="0" class="datatable table table-striped table-bordered table-hover">
								<thead>
									<tr>
										<th>Month</th>
										<th>Number of Signings</th>
										<th class="hidden-xs">Income Generated</th>
										<th>Expenses Incurred</th>
										<th class="hidden-xs">%ge of Year X</th>
									</tr>
								</thead>
								<tbody>
									<tr class="gradeX">
										<td>Trident</td>
										<td>
											Internet
											 Explorer
											4.0
											</td>
										<td class="hidden-xs">Win 95+</td>
										<td class="center">4</td>
										<td class="center hidden-xs">X</td>
									</tr>
									<tr class="gradeC">
										<td>Trident</td>
										<td>Internet
											 Explorer 5.0</td>
										<td class="hidden-xs">Win 95+</td>
										<td class="center">5</td>
										<td class="center hidden-xs">C</td>
									</tr>
									<tr class="gradeA">
										<td>Trident</td>
										<td>Internet
											 Explorer 5.5</td>
										<td class="hidden-xs">Win 95+</td>
										<td class="center">5.5</td>
										<td class="center hidden-xs">A</td>
									</tr>
									<tr class="gradeA">
										<td>Trident</td>
										<td>Internet
											 Explorer 6</td>
										<td class="hidden-xs">Win 98+</td>
										<td class="center">6</td>
										<td class="center hidden-xs">A</td>
									</tr>
									<tr class="gradeA">
										<td>Trident</td>
										<td>Internet Explorer 7</td>
										<td class="hidden-xs">Win XP SP2+</td>
										<td class="center">7</td>
										<td class="center hidden-xs">A</td>
									</tr>
									<tr class="gradeA">
										<td>Trident</td>
										<td>AOL browser (AOL desktop)</td>
										<td class="hidden-xs">Win XP</td>
										<td class="center">6</td>
										<td class="center hidden-xs">A</td>
									</tr>
									<tr class="gradeA">
										<td>Gecko</td>
										<td>Firefox 1.0</td>
										<td class="hidden-xs">Win 98+ / OSX.2+</td>
										<td class="center">1.7</td>
										<td class="center hidden-xs">A</td>
									</tr>
									<tr class="gradeA">
										<td>Gecko</td>
										<td>Firefox 1.5</td>
										<td class="hidden-xs">Win 98+ / OSX.2+</td>
										<td class="center">1.8</td>
										<td class="center hidden-xs">A</td>
									</tr>
									<tr class="gradeA">
										<td>Gecko</td>
										<td>Firefox 2.0</td>
										<td class="hidden-xs">Win 98+ / OSX.2+</td>
										<td class="center">1.8</td>
										<td class="center hidden-xs">A</td>
									</tr>
									<tr class="gradeA">
										<td>Gecko</td>
										<td>Firefox 3.0</td>
										<td class="hidden-xs">Win 2k+ / OSX.3+</td>
										<td class="center">1.9</td>
										<td class="center hidden-xs">A</td>
									</tr>
									<tr class="gradeA">
										<td>Gecko</td>
										<td>Camino 1.0</td>
										<td class="hidden-xs">OSX.2+</td>
										<td class="center">1.8</td>
										<td class="center hidden-xs">A</td>
									</tr>
									<tr class="gradeA">
										<td>Gecko</td>
										<td>Camino 1.5</td>
										<td class="hidden-xs">OSX.3+</td>
										<td class="center">1.8</td>
										<td class="center hidden-xs">A</td>
									</tr>
									<tr class="gradeA">
										<td>Gecko</td>
										<td>Netscape 7.2</td>
										<td class="hidden-xs">Win 95+ / Mac OS 8.6-9.2</td>
										<td class="center">1.7</td>
										<td class="center hidden-xs">A</td>
									</tr>
									<tr class="gradeA">
										<td>Gecko</td>
										<td>Netscape Browser 8</td>
										<td class="hidden-xs">Win 98SE+</td>
										<td class="center">1.7</td>
										<td class="center hidden-xs">A</td>
									</tr>
									<tr class="gradeA">
										<td>Gecko</td>
										<td>Netscape Navigator 9</td>
										<td class="hidden-xs">Win 98+ / OSX.2+</td>
										<td class="center">1.8</td>
										<td class="center hidden-xs">A</td>
									</tr>
									<tr class="gradeA">
										<td>Gecko</td>
										<td>Mozilla 1.0</td>
										<td class="hidden-xs">Win 95+ / OSX.1+</td>
										<td class="center">1</td>
										<td class="center hidden-xs">A</td>
									</tr>
									<tr class="gradeA">
										<td>Gecko</td>
										<td>Mozilla 1.1</td>
										<td class="hidden-xs">Win 95+ / OSX.1+</td>
										<td class="center">1.1</td>
										<td class="center hidden-xs">A</td>
									</tr>
									<tr class="gradeA">
										<td>Gecko</td>
										<td>Mozilla 1.2</td>
										<td class="hidden-xs">Win 95+ / OSX.1+</td>
										<td class="center">1.2</td>
										<td class="center hidden-xs">A</td>
									</tr>
									<tr class="gradeA">
										<td>Gecko</td>
										<td>Mozilla 1.3</td>
										<td class="hidden-xs">Win 95+ / OSX.1+</td>
										<td class="center">1.3</td>
										<td class="center hidden-xs">A</td>
									</tr>
									<tr class="gradeA">
										<td>Gecko</td>
										<td>Mozilla 1.4</td>
										<td class="hidden-xs">Win 95+ / OSX.1+</td>
										<td class="center">1.4</td>
										<td class="center hidden-xs">A</td>
									</tr>
									<tr class="gradeA">
										<td>Gecko</td>
										<td>Mozilla 1.5</td>
										<td class="hidden-xs">Win 95+ / OSX.1+</td>
										<td class="center">1.5</td>
										<td class="center hidden-xs">A</td>
									</tr>
									<tr class="gradeA">
										<td>Gecko</td>
										<td>Mozilla 1.6</td>
										<td class="hidden-xs">Win 95+ / OSX.1+</td>
										<td class="center">1.6</td>
										<td class="center hidden-xs">A</td>
									</tr>
									<tr class="gradeA">
										<td>Gecko</td>
										<td>Mozilla 1.7</td>
										<td class="hidden-xs">Win 98+ / OSX.1+</td>
										<td class="center">1.7</td>
										<td class="center hidden-xs">A</td>
									</tr>
									<tr class="gradeA">
										<td>Gecko</td>
										<td>Mozilla 1.8</td>
										<td class="hidden-xs">Win 98+ / OSX.1+</td>
										<td class="center">1.8</td>
										<td class="center hidden-xs">A</td>
									</tr>
									<tr class="gradeA">
										<td>Gecko</td>
										<td>Seamonkey 1.1</td>
										<td class="hidden-xs">Win 98+ / OSX.2+</td>
										<td class="center">1.8</td>
										<td class="center hidden-xs">A</td>
									</tr>
									<tr class="gradeA">
										<td>Gecko</td>
										<td>Epiphany 2.20</td>
										<td class="hidden-xs">Gnome</td>
										<td class="center">1.8</td>
										<td class="center hidden-xs">A</td>
									</tr>
									<tr class="gradeA">
										<td>Webkit</td>
										<td>Safari 1.2</td>
										<td class="hidden-xs">OSX.3</td>
										<td class="center">125.5</td>
										<td class="center hidden-xs">A</td>
									</tr>
									<tr class="gradeA">
										<td>Webkit</td>
										<td>Safari 1.3</td>
										<td class="hidden-xs">OSX.3</td>
										<td class="center">312.8</td>
										<td class="center hidden-xs">A</td>
									</tr>
									<tr class="gradeA">
										<td>Webkit</td>
										<td>Safari 2.0</td>
										<td class="hidden-xs">OSX.4+</td>
										<td class="center">419.3</td>
										<td class="center hidden-xs">A</td>
									</tr>
									<tr class="gradeA">
										<td>Webkit</td>
										<td>Safari 3.0</td>
										<td class="hidden-xs">OSX.4+</td>
										<td class="center">522.1</td>
										<td class="center hidden-xs">A</td>
									</tr>
									<tr class="gradeA">
										<td>Webkit</td>
										<td>OmniWeb 5.5</td>
										<td class="hidden-xs">OSX.4+</td>
										<td class="center">420</td>
										<td class="center hidden-xs">A</td>
									</tr>
									<tr class="gradeA">
										<td>Webkit</td>
										<td>iPod Touch / iPhone</td>
										<td class="hidden-xs">iPod</td>
										<td class="center">420.1</td>
										<td class="center hidden-xs">A</td>
									</tr>
									<tr class="gradeA">
										<td>Webkit</td>
										<td>S60</td>
										<td class="hidden-xs">S60</td>
										<td class="center">413</td>
										<td class="center hidden-xs">A</td>
									</tr>
									<tr class="gradeA">
										<td>Presto</td>
										<td>Opera 7.0</td>
										<td class="hidden-xs">Win 95+ / OSX.1+</td>
										<td class="center">-</td>
										<td class="center hidden-xs">A</td>
									</tr>
									<tr class="gradeA">
										<td>Presto</td>
										<td>Opera 7.5</td>
										<td class="hidden-xs">Win 95+ / OSX.2+</td>
										<td class="center">-</td>
										<td class="center hidden-xs">A</td>
									</tr>
									<tr class="gradeA">
										<td>Presto</td>
										<td>Opera 8.0</td>
										<td class="hidden-xs">Win 95+ / OSX.2+</td>
										<td class="center">-</td>
										<td class="center hidden-xs">A</td>
									</tr>
									<tr class="gradeA">
										<td>Presto</td>
										<td>Opera 8.5</td>
										<td class="hidden-xs">Win 95+ / OSX.2+</td>
										<td class="center">-</td>
										<td class="center hidden-xs">A</td>
									</tr>
									<tr class="gradeA">
										<td>Presto</td>
										<td>Opera 9.0</td>
										<td class="hidden-xs">Win 95+ / OSX.3+</td>
										<td class="center">-</td>
										<td class="center hidden-xs">A</td>
									</tr>
									<tr class="gradeA">
										<td>Presto</td>
										<td>Opera 9.2</td>
										<td class="hidden-xs">Win 88+ / OSX.3+</td>
										<td class="center">-</td>
										<td class="center hidden-xs">A</td>
									</tr>
									<tr class="gradeA">
										<td>Presto</td>
										<td>Opera 9.5</td>
										<td class="hidden-xs">Win 88+ / OSX.3+</td>
										<td class="center">-</td>
										<td class="center hidden-xs">A</td>
									</tr>
									<tr class="gradeA">
										<td>Presto</td>
										<td>Opera for Wii</td>
										<td class="hidden-xs">Wii</td>
										<td class="center">-</td>
										<td class="center hidden-xs">A</td>
									</tr>
									<tr class="gradeA">
										<td>Presto</td>
										<td>Nokia N800</td>
										<td class="hidden-xs">N800</td>
										<td class="center">-</td>
										<td class="center hidden-xs">A</td>
									</tr>
									<tr class="gradeA">
										<td>Presto</td>
										<td>Nintendo DS browser</td>
										<td class="hidden-xs">Nintendo DS</td>
										<td class="center">8.5</td>
										<td class="center hidden-xs">C/A<sup>1</sup></td>
									</tr>
									<tr class="gradeC">
										<td>KHTML</td>
										<td>Konqureror 3.1</td>
										<td class="hidden-xs">KDE 3.1</td>
										<td class="center">3.1</td>
										<td class="center hidden-xs">C</td>
									</tr>
									<tr class="gradeA">
										<td>KHTML</td>
										<td>Konqureror 3.3</td>
										<td class="hidden-xs">KDE 3.3</td>
										<td class="center">3.3</td>
										<td class="center hidden-xs">A</td>
									</tr>
									<tr class="gradeA">
										<td>KHTML</td>
										<td>Konqureror 3.5</td>
										<td class="hidden-xs">KDE 3.5</td>
										<td class="center">3.5</td>
										<td class="center hidden-xs">A</td>
									</tr>
									<tr class="gradeX">
										<td>Tasman</td>
										<td>Internet Explorer 4.5</td>
										<td class="hidden-xs">Mac OS 8-9</td>
										<td class="center">-</td>
										<td class="center hidden-xs">X</td>
									</tr>
									<tr class="gradeC">
										<td>Tasman</td>
										<td>Internet Explorer 5.1</td>
										<td class="hidden-xs">Mac OS 7.6-9</td>
										<td class="center">1</td>
										<td class="center hidden-xs">C</td>
									</tr>
									<tr class="gradeC">
										<td>Tasman</td>
										<td>Internet Explorer 5.2</td>
										<td class="hidden-xs">Mac OS 8-X</td>
										<td class="center">1</td>
										<td class="center hidden-xs">C</td>
									</tr>
									<tr class="gradeA">
										<td>Misc</td>
										<td>NetFront 3.1</td>
										<td class="hidden-xs">Embedded devices</td>
										<td class="center">-</td>
										<td class="center hidden-xs">C</td>
									</tr>
									<tr class="gradeA">
										<td>Misc</td>
										<td>NetFront 3.4</td>
										<td class="hidden-xs">Embedded devices</td>
										<td class="center">-</td>
										<td class="center hidden-xs">A</td>
									</tr>
									<tr class="gradeX">
										<td>Misc</td>
										<td>Dillo 0.8</td>
										<td class="hidden-xs">Embedded devices</td>
										<td class="center">-</td>
										<td class="center hidden-xs">X</td>
									</tr>
									<tr class="gradeX">
										<td>Misc</td>
										<td>Links</td>
										<td class="hidden-xs">Text only</td>
										<td class="center">-</td>
										<td class="center hidden-xs">X</td>
									</tr>
									<tr class="gradeX">
										<td>Misc</td>
										<td>Lynx</td>
										<td class="hidden-xs">Text only</td>
										<td class="center">-</td>
										<td class="center hidden-xs">X</td>
									</tr>
									<tr class="gradeC">
										<td>Misc</td>
										<td>IE Mobile</td>
										<td class="hidden-xs">Windows Mobile 6</td>
										<td class="center">-</td>
										<td class="center hidden-xs">C</td>
									</tr>
									<tr class="gradeC">
										<td>Misc</td>
										<td>PSP browser</td>
										<td class="hidden-xs">PSP</td>
										<td class="center">-</td>
										<td class="center hidden-xs">C</td>
									</tr>
									<tr class="gradeU">
										<td>Other browsers</td>
										<td class="hidden-xs">All others</td>
										<td>-</td>
										<td class="center">-</td>
										<td class="center hidden-xs">U</td>
									</tr>
								</tbody>
								<tfoot>
									<tr>
										<th>Month</th>
										<th>Number of Signings</th>
										<th class="hidden-xs">Income Generated</th>
										<th>Expenses Incurred</th>
										<th class="hidden-xs">%ge of Year X</th>
									</tr>
								</tfoot>
							</table>
						</div>
					</div>
					<!-- /BOX -->
				</div>
			</div>
		   <!-- /Second Row CONTENT -->


					<div class="separator"></div>

			<!-- Third Row CONTENT -->
			<div class="row">
				<div class="col-md-12">
					<!-- BOX -->
					<div class="box border blue">
						<div class="box-title">
							<h4><i class="fa fa-table"></i>2002-2014 Top 5 Signing Sources by Orders</h4>
							<div class="tools hidden-xs">
								<a href="#box-config" data-toggle="modal" class="config">
									<i class="fa fa-cog"></i>
								</a>
								<a href="javascript:;" class="reload">
									<i class="fa fa-refresh"></i>
								</a>
								<a href="javascript:;" class="collapse">
									<i class="fa fa-chevron-up"></i>
								</a>
							</div>
						</div>

						<div class="box-body">
							<table id="datatable2" cellpadding="0" cellspacing="0" border="0" class="datatable table table-striped table-bordered table-hover">
								<thead>
									<tr>
										<th>Month</th>
										<th>Number of Signings</th>
										<th class="hidden-xs">Income Generated</th>
										<th>Expenses Incurred</th>
										<th class="hidden-xs">%ge of Year X</th>
									</tr>
								</thead>
								<tbody>
									<tr class="gradeX">
										<td>Trident</td>
										<td>
											Internet
											 Explorer
											4.0
											</td>
										<td class="hidden-xs">Win 95+</td>
										<td class="center">4</td>
										<td class="center hidden-xs">X</td>
									</tr>
									<tr class="gradeC">
										<td>Trident</td>
										<td>Internet
											 Explorer 5.0</td>
										<td class="hidden-xs">Win 95+</td>
										<td class="center">5</td>
										<td class="center hidden-xs">C</td>
									</tr>
									<tr class="gradeA">
										<td>Trident</td>
										<td>Internet
											 Explorer 5.5</td>
										<td class="hidden-xs">Win 95+</td>
										<td class="center">5.5</td>
										<td class="center hidden-xs">A</td>
									</tr>
									<tr class="gradeA">
										<td>Trident</td>
										<td>Internet
											 Explorer 6</td>
										<td class="hidden-xs">Win 98+</td>
										<td class="center">6</td>
										<td class="center hidden-xs">A</td>
									</tr>
									<tr class="gradeA">
										<td>Trident</td>
										<td>Internet Explorer 7</td>
										<td class="hidden-xs">Win XP SP2+</td>
										<td class="center">7</td>
										<td class="center hidden-xs">A</td>
									</tr>
									<tr class="gradeA">
										<td>Trident</td>
										<td>AOL browser (AOL desktop)</td>
										<td class="hidden-xs">Win XP</td>
										<td class="center">6</td>
										<td class="center hidden-xs">A</td>
									</tr>
									<tr class="gradeA">
										<td>Gecko</td>
										<td>Firefox 1.0</td>
										<td class="hidden-xs">Win 98+ / OSX.2+</td>
										<td class="center">1.7</td>
										<td class="center hidden-xs">A</td>
									</tr>
									<tr class="gradeA">
										<td>Gecko</td>
										<td>Firefox 1.5</td>
										<td class="hidden-xs">Win 98+ / OSX.2+</td>
										<td class="center">1.8</td>
										<td class="center hidden-xs">A</td>
									</tr>
									<tr class="gradeA">
										<td>Gecko</td>
										<td>Firefox 2.0</td>
										<td class="hidden-xs">Win 98+ / OSX.2+</td>
										<td class="center">1.8</td>
										<td class="center hidden-xs">A</td>
									</tr>
									<tr class="gradeA">
										<td>Gecko</td>
										<td>Firefox 3.0</td>
										<td class="hidden-xs">Win 2k+ / OSX.3+</td>
										<td class="center">1.9</td>
										<td class="center hidden-xs">A</td>
									</tr>
									<tr class="gradeA">
										<td>Gecko</td>
										<td>Camino 1.0</td>
										<td class="hidden-xs">OSX.2+</td>
										<td class="center">1.8</td>
										<td class="center hidden-xs">A</td>
									</tr>
									<tr class="gradeA">
										<td>Gecko</td>
										<td>Camino 1.5</td>
										<td class="hidden-xs">OSX.3+</td>
										<td class="center">1.8</td>
										<td class="center hidden-xs">A</td>
									</tr>
									<tr class="gradeA">
										<td>Gecko</td>
										<td>Netscape 7.2</td>
										<td class="hidden-xs">Win 95+ / Mac OS 8.6-9.2</td>
										<td class="center">1.7</td>
										<td class="center hidden-xs">A</td>
									</tr>
									<tr class="gradeA">
										<td>Gecko</td>
										<td>Netscape Browser 8</td>
										<td class="hidden-xs">Win 98SE+</td>
										<td class="center">1.7</td>
										<td class="center hidden-xs">A</td>
									</tr>
									<tr class="gradeA">
										<td>Gecko</td>
										<td>Netscape Navigator 9</td>
										<td class="hidden-xs">Win 98+ / OSX.2+</td>
										<td class="center">1.8</td>
										<td class="center hidden-xs">A</td>
									</tr>
									<tr class="gradeA">
										<td>Gecko</td>
										<td>Mozilla 1.0</td>
										<td class="hidden-xs">Win 95+ / OSX.1+</td>
										<td class="center">1</td>
										<td class="center hidden-xs">A</td>
									</tr>
									<tr class="gradeA">
										<td>Gecko</td>
										<td>Mozilla 1.1</td>
										<td class="hidden-xs">Win 95+ / OSX.1+</td>
										<td class="center">1.1</td>
										<td class="center hidden-xs">A</td>
									</tr>
									<tr class="gradeA">
										<td>Gecko</td>
										<td>Mozilla 1.2</td>
										<td class="hidden-xs">Win 95+ / OSX.1+</td>
										<td class="center">1.2</td>
										<td class="center hidden-xs">A</td>
									</tr>
									<tr class="gradeA">
										<td>Gecko</td>
										<td>Mozilla 1.3</td>
										<td class="hidden-xs">Win 95+ / OSX.1+</td>
										<td class="center">1.3</td>
										<td class="center hidden-xs">A</td>
									</tr>
									<tr class="gradeA">
										<td>Gecko</td>
										<td>Mozilla 1.4</td>
										<td class="hidden-xs">Win 95+ / OSX.1+</td>
										<td class="center">1.4</td>
										<td class="center hidden-xs">A</td>
									</tr>
									<tr class="gradeA">
										<td>Gecko</td>
										<td>Mozilla 1.5</td>
										<td class="hidden-xs">Win 95+ / OSX.1+</td>
										<td class="center">1.5</td>
										<td class="center hidden-xs">A</td>
									</tr>
									<tr class="gradeA">
										<td>Gecko</td>
										<td>Mozilla 1.6</td>
										<td class="hidden-xs">Win 95+ / OSX.1+</td>
										<td class="center">1.6</td>
										<td class="center hidden-xs">A</td>
									</tr>
									<tr class="gradeA">
										<td>Gecko</td>
										<td>Mozilla 1.7</td>
										<td class="hidden-xs">Win 98+ / OSX.1+</td>
										<td class="center">1.7</td>
										<td class="center hidden-xs">A</td>
									</tr>
									<tr class="gradeA">
										<td>Gecko</td>
										<td>Mozilla 1.8</td>
										<td class="hidden-xs">Win 98+ / OSX.1+</td>
										<td class="center">1.8</td>
										<td class="center hidden-xs">A</td>
									</tr>
									<tr class="gradeA">
										<td>Gecko</td>
										<td>Seamonkey 1.1</td>
										<td class="hidden-xs">Win 98+ / OSX.2+</td>
										<td class="center">1.8</td>
										<td class="center hidden-xs">A</td>
									</tr>
									<tr class="gradeA">
										<td>Gecko</td>
										<td>Epiphany 2.20</td>
										<td class="hidden-xs">Gnome</td>
										<td class="center">1.8</td>
										<td class="center hidden-xs">A</td>
									</tr>
									<tr class="gradeA">
										<td>Webkit</td>
										<td>Safari 1.2</td>
										<td class="hidden-xs">OSX.3</td>
										<td class="center">125.5</td>
										<td class="center hidden-xs">A</td>
									</tr>
									<tr class="gradeA">
										<td>Webkit</td>
										<td>Safari 1.3</td>
										<td class="hidden-xs">OSX.3</td>
										<td class="center">312.8</td>
										<td class="center hidden-xs">A</td>
									</tr>
									<tr class="gradeA">
										<td>Webkit</td>
										<td>Safari 2.0</td>
										<td class="hidden-xs">OSX.4+</td>
										<td class="center">419.3</td>
										<td class="center hidden-xs">A</td>
									</tr>
									<tr class="gradeA">
										<td>Webkit</td>
										<td>Safari 3.0</td>
										<td class="hidden-xs">OSX.4+</td>
										<td class="center">522.1</td>
										<td class="center hidden-xs">A</td>
									</tr>
									<tr class="gradeA">
										<td>Webkit</td>
										<td>OmniWeb 5.5</td>
										<td class="hidden-xs">OSX.4+</td>
										<td class="center">420</td>
										<td class="center hidden-xs">A</td>
									</tr>
									<tr class="gradeA">
										<td>Webkit</td>
										<td>iPod Touch / iPhone</td>
										<td class="hidden-xs">iPod</td>
										<td class="center">420.1</td>
										<td class="center hidden-xs">A</td>
									</tr>
									<tr class="gradeA">
										<td>Webkit</td>
										<td>S60</td>
										<td class="hidden-xs">S60</td>
										<td class="center">413</td>
										<td class="center hidden-xs">A</td>
									</tr>
									<tr class="gradeA">
										<td>Presto</td>
										<td>Opera 7.0</td>
										<td class="hidden-xs">Win 95+ / OSX.1+</td>
										<td class="center">-</td>
										<td class="center hidden-xs">A</td>
									</tr>
									<tr class="gradeA">
										<td>Presto</td>
										<td>Opera 7.5</td>
										<td class="hidden-xs">Win 95+ / OSX.2+</td>
										<td class="center">-</td>
										<td class="center hidden-xs">A</td>
									</tr>
									<tr class="gradeA">
										<td>Presto</td>
										<td>Opera 8.0</td>
										<td class="hidden-xs">Win 95+ / OSX.2+</td>
										<td class="center">-</td>
										<td class="center hidden-xs">A</td>
									</tr>
									<tr class="gradeA">
										<td>Presto</td>
										<td>Opera 8.5</td>
										<td class="hidden-xs">Win 95+ / OSX.2+</td>
										<td class="center">-</td>
										<td class="center hidden-xs">A</td>
									</tr>
									<tr class="gradeA">
										<td>Presto</td>
										<td>Opera 9.0</td>
										<td class="hidden-xs">Win 95+ / OSX.3+</td>
										<td class="center">-</td>
										<td class="center hidden-xs">A</td>
									</tr>
									<tr class="gradeA">
										<td>Presto</td>
										<td>Opera 9.2</td>
										<td class="hidden-xs">Win 88+ / OSX.3+</td>
										<td class="center">-</td>
										<td class="center hidden-xs">A</td>
									</tr>
									<tr class="gradeA">
										<td>Presto</td>
										<td>Opera 9.5</td>
										<td class="hidden-xs">Win 88+ / OSX.3+</td>
										<td class="center">-</td>
										<td class="center hidden-xs">A</td>
									</tr>
									<tr class="gradeA">
										<td>Presto</td>
										<td>Opera for Wii</td>
										<td class="hidden-xs">Wii</td>
										<td class="center">-</td>
										<td class="center hidden-xs">A</td>
									</tr>
									<tr class="gradeA">
										<td>Presto</td>
										<td>Nokia N800</td>
										<td class="hidden-xs">N800</td>
										<td class="center">-</td>
										<td class="center hidden-xs">A</td>
									</tr>
									<tr class="gradeA">
										<td>Presto</td>
										<td>Nintendo DS browser</td>
										<td class="hidden-xs">Nintendo DS</td>
										<td class="center">8.5</td>
										<td class="center hidden-xs">C/A<sup>1</sup></td>
									</tr>
									<tr class="gradeC">
										<td>KHTML</td>
										<td>Konqureror 3.1</td>
										<td class="hidden-xs">KDE 3.1</td>
										<td class="center">3.1</td>
										<td class="center hidden-xs">C</td>
									</tr>
									<tr class="gradeA">
										<td>KHTML</td>
										<td>Konqureror 3.3</td>
										<td class="hidden-xs">KDE 3.3</td>
										<td class="center">3.3</td>
										<td class="center hidden-xs">A</td>
									</tr>
									<tr class="gradeA">
										<td>KHTML</td>
										<td>Konqureror 3.5</td>
										<td class="hidden-xs">KDE 3.5</td>
										<td class="center">3.5</td>
										<td class="center hidden-xs">A</td>
									</tr>
									<tr class="gradeX">
										<td>Tasman</td>
										<td>Internet Explorer 4.5</td>
										<td class="hidden-xs">Mac OS 8-9</td>
										<td class="center">-</td>
										<td class="center hidden-xs">X</td>
									</tr>
									<tr class="gradeC">
										<td>Tasman</td>
										<td>Internet Explorer 5.1</td>
										<td class="hidden-xs">Mac OS 7.6-9</td>
										<td class="center">1</td>
										<td class="center hidden-xs">C</td>
									</tr>
									<tr class="gradeC">
										<td>Tasman</td>
										<td>Internet Explorer 5.2</td>
										<td class="hidden-xs">Mac OS 8-X</td>
										<td class="center">1</td>
										<td class="center hidden-xs">C</td>
									</tr>
									<tr class="gradeA">
										<td>Misc</td>
										<td>NetFront 3.1</td>
										<td class="hidden-xs">Embedded devices</td>
										<td class="center">-</td>
										<td class="center hidden-xs">C</td>
									</tr>
									<tr class="gradeA">
										<td>Misc</td>
										<td>NetFront 3.4</td>
										<td class="hidden-xs">Embedded devices</td>
										<td class="center">-</td>
										<td class="center hidden-xs">A</td>
									</tr>
									<tr class="gradeX">
										<td>Misc</td>
										<td>Dillo 0.8</td>
										<td class="hidden-xs">Embedded devices</td>
										<td class="center">-</td>
										<td class="center hidden-xs">X</td>
									</tr>
									<tr class="gradeX">
										<td>Misc</td>
										<td>Links</td>
										<td class="hidden-xs">Text only</td>
										<td class="center">-</td>
										<td class="center hidden-xs">X</td>
									</tr>
									<tr class="gradeX">
										<td>Misc</td>
										<td>Lynx</td>
										<td class="hidden-xs">Text only</td>
										<td class="center">-</td>
										<td class="center hidden-xs">X</td>
									</tr>
									<tr class="gradeC">
										<td>Misc</td>
										<td>IE Mobile</td>
										<td class="hidden-xs">Windows Mobile 6</td>
										<td class="center">-</td>
										<td class="center hidden-xs">C</td>
									</tr>
									<tr class="gradeC">
										<td>Misc</td>
										<td>PSP browser</td>
										<td class="hidden-xs">PSP</td>
										<td class="center">-</td>
										<td class="center hidden-xs">C</td>
									</tr>
									<tr class="gradeU">
										<td>Other browsers</td>
										<td class="hidden-xs">All others</td>
										<td>-</td>
										<td class="center">-</td>
										<td class="center hidden-xs">U</td>
									</tr>
								</tbody>
								<tfoot>
									<tr>
										<th>Month</th>
										<th>Number of Signings</th>
										<th class="hidden-xs">Income Generated</th>
										<th>Expenses Incurred</th>
										<th class="hidden-xs">%ge of Year X</th>
									</tr>
								</tfoot>
							</table>
						</div>
					</div>
					<!-- /BOX -->
				</div>
			</div>
		   <!-- /Third Row CONTENT -->



			<!-- Fourth Row CONTENT -->
			<div class="row">

			</div>
		   <!-- /Fourth Row CONTENT -->


			<div class="separator"></div>
			<div class="footer-tools">
				<span class="go-top">
					<i class="fa fa-chevron-up"></i> Top
				</span>
			</div>
		</div><!-- /CONTENT-->
	</div>
</div>