<?php echo $this->doctype(); ?>

<!--[if IE 7]>					<html class="ie7 no-js" lang="en">     <![endif]-->
<!--[if lte IE 8]>              <html class="ie8 no-js" lang="en">     <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html class="not-ie no-js" lang="en">  <!--<![endif]-->

<head>
	<!-- Basic Page Needs
    ================================================== -->
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <?php echo $this->headTitle('Nomsterz - track, analyze, visualize.')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0, maximum-scale=1')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge,IE=9,IE=8,chrome=1')
        ->appendName('description', '')
        ->appendName('author', '')
    ?>

    <?php echo $this->headLink
                    (
                        array
                        (
                            'rel'   =>  'shortcut icon',
                            'type'  =>  'image/vnd.microsoft.icon',
                            'href'  =>  $this->basePath() . '/application/images/favicon.ico'
                        )
                    )
                    ->prependStylesheet($this->basePath() . '/application/js/fancybox/jquery.fancybox.css')
                    ->prependStylesheet($this->basePath() . '/application/js/layerslider/css/layerslider.css')
                    ->prependStylesheet($this->basePath() . '/application/css/font-awesome.css')
                    ->prependStylesheet($this->basePath() . '/application/css/layout.css')
                    ->prependStylesheet($this->basePath() . '/application/css/skeleton.css')
                    ->prependStylesheet($this->basePath() . '/application/css/style.css')
                    ->prependStylesheet('http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,600italic|Handlee')
    ?>

    <?php echo $this->headScript()
                    ->prependFile($this->basePath() . '/application/js/jquery.modernizr.js')
    ; ?>

</head>

<body class="wide normal pattern-1 color-16">

<div id="wrapper">

    <header id="header">

        <div class="container">

			<div class="eight columns">

				<div id="logo">
					<a href="<?php echo $this->url('home') ?>">
                        <img src="<?php echo $this->basePath(); ?>/application/images/logo.png"  alt="logo">
                    </a>
				</div>
                <!--/ #logo-->

			</div><!--/ .columns-->

			<div class="eight columns">

				<div class="widget widget_contacts">

					<div class="vcard clearfix">

						<p class="top-phone">Call Us : <span>+00 123456789</span></p>
						<p class="top-email"><a class="email" href="mailto:info@nomsterz.com">info@nomsterz.com</a></p>

					</div><!--/ .vcard-->

					<div class="clear"></div>

					<ul class="social-icons">
						<li class="twitter" > <a href="https://www.Twitter.com/" target="_blank" title="Twitter"></a></li>
						<li class="facebook"> <a href="https://www.Facebook.com/" target="_blank" title="Facebook"></a></li>
						<li class="linkedin"> <a href="https://www.LinkedIn.com/" target="_blank" title="LinkedIn"></a></li>
						<li class="pinterest"><a href="https://www.Pinterest.com/" target="_blank" title="Pinterest"></a></li>
						<li class="vimeo"   > <a href="https://www.Vimeo.com/" target="_blank" title="Vimeo"></a></li>
						<li class="youtube" > <a href="https://www.Youtube.com/" target="_blank" title="Youtube"></a></li>
					</ul><!--/ .social-icons -->

				</div>

			</div><!--/ .columns-->

			<div class="clear"></div>

			<div class="sixteen columns">

				<div class="menu-container clearfix">

					<nav id="navigation" class="navigation">

						<div class="menu">
							<ul>
								<li class="current-menu-item">
                                    <a href="<?php echo $this->url('home') ?>">Home</a>
								</li>
								<li>
                                    <a href="<?php echo $this->url('what-we-do-for-notaries'); ?>">What We Do</a>
									<ul>
										<li>
                                            <a href="<?php echo $this->url('what-we-do-for-notaries'); ?>">For Notaries Public</a>
										</li>
										<li>
                                            <a href="<?php echo $this->url('what-we-do-for-signing-agencies'); ?>">For Signing Agencies</a>
										</li>
										<li>
                                            <a href="<?php echo $this->url('what-we-do-for-lenders'); ?>">For Lenders</a>
										</li>
									</ul>
								</li>
								<li>
                                    <a href="">Who We Are</a>
									<ul>
										<li><a href="">About Us</a></li>
										<li><a href="">The Team</a></li>
									</ul>
								</li>
								<li><a href="">How Much</a>
								</li>
								<li><a href="">Features</a>
									<ul>
										<li><a href="">???</a></li>
										<li><a href="">???</a></li>
										<li><a href="">???</a></li>
										<li><a href="">???</a></li>
										<li><a href="">???</a></li>
										<li><a href="">???</a></li>
										<li><a href="">???</a></li>
										<li><a href="<?php echo $this->url('admin'); ?>">???</a></li>
									</ul>
								</li>
								<li>
                                    <a href="">Our Blog</a>
								</li>
								<li>
                                    <a href="<?php echo $this->url('contact-us-faq'); ?>">Contact Us</a>
									<ul>
										<li><a href="<?php echo $this->url('contact-us-faq'); ?>">FAQ</a></li>
										<li><a href="<?php echo $this->url('contact-us-suggestions'); ?>">Suggestions</a></li>
										<li><a href="<?php echo $this->url('contact-us-customer-support'); ?>">Customer Support</a></li>
									</ul>
                                </li>
								<li>
                                    <a href="<?php echo $this->url('member-login'); ?>">LOGIN</a>
								</li>
								<li>
                                    <a href="<?php echo $this->url('member-signup'); ?>">Signup</a>
								</li>
							</ul>
						</div>

					</nav><!--/ .navigation-->

				</div><!--/ .menu-container-->

			</div><!--/ .columns-->

		</div><!--/ .container-->

    </header><!--/ #header-->

    <?php echo $this->content; ?>

	<footer id="footer">

		<div class="container">

			<div class="four columns">

				<div class="widget widget_text">

					<h3 class="widget-title">About Us</h3>

					<div class="textwidget">

						<p>
							Risus mollis malesuada quis quis nulla. Vestibulum ante ipsum primis in faucibus
							orci luctus et ultrices posuere cubilia mattis vel elit porttitor euismod pharetra
							sem interdum.
						</p>
						<p>
							Etiam laoreet sagittis placerat magna sit amet massa posuere pretiumulum id est
							nulla, non adipiscing tortor.
						</p>

					</div><!--/ .textwidget-->

				</div><!--/ .widget -->

			</div><!--/ .columns -->

			<div class="four columns">

				<div class="widget widget_recent_entries">

					<h3 class="widget-title">Recent Posts</h3>

					<ul>
						<li>
							<a title="Single Clean Post" href="blog.html">Single Clean Post</a>
							<span class="post-date">June 3, 2013</span>
						</li>
						<li>
							<a title="Post With Custom Slideshow" href="blog.html">Post With Custom Slideshow</a>
							<span class="post-date">June 3, 2013</span>
						</li>
						<li>
							<a title="Video Post Format" href="blog.html">Video Post Format</a>
							<span class="post-date">June 3, 2013</span>
						</li>
						<li>
							<a title="Post Without Image" href="blog.html">Post Without Image</a>
							<span class="post-date">June 3, 2013</span>
						</li>
					</ul>

				</div><!--/ .widget-->

			</div><!--/ .columns-->

			<div class="four columns">

				<div class="widget widget_tag_cloud">

					<h3 class="widget-title">Tag Cloud</h3>

					<div class="tagcloud">
						<a href="#">Audio</a>
						<a href="#">Design</a>
						<a href="#">Features</a>
						<a href="#">Logo</a>
						<a href="#">Photo</a>
						<a href="#">Photography</a>
						<a href="#">Video</a>
						<a href="#">Web</a>
					</div><!--/ .tagcloud-->

				</div><!--/ .widget-->

				<div class="widget widget_social">

					<h3 class="widget-title">Social Links</h3>

					<ul class="social-icons clearfix">

						<li class="twitter">
							<a href="https://twitter.com" target="_blank" title="Twitter"></a>
						</li>

						<li class="facebook">
							<a href="http://www.facebook.com" target="_blank" title="Facebook"></a>
						</li>

						<li class="linkedin">
							<a href="http://linkedin.com/" target="_blank" title="LinkedIn"></a>
						</li>

						<li class="pinterest">
							<a href="http://pinterest.com/" target="_blank" title="Pinterest"></a>
						</li>

						<li class="vimeo">
							<a href="https://vimeo.com/" target="_blank" title="Vimeo"></a>
						</li>

						<li class="youtube">
							<a href="http://www.youtube.com" target="_blank" title="YouTube"></a>
						</li>

					</ul><!--/ .social-list-->

				</div><!--/ .widget-->

			</div><!--/ .columns -->

			<div class="four columns">

				<div class="widget widget_flickr">

					<h3 class="widget-title">Photo Stream</h3>

					<ul class="flickr-badge clearfix"></ul>

				</div><!--/ .widget -->

			</div><!--/ .columns -->

			<div class="clear"></div>

			<div class="sixteen columns">

				<div class="adjective clearfix">
					<div class="copyright" >Copyright © 2010 - <?php echo date('Y'); ?>. Nomsterz. All rights reserved</div>
					<div class="developed"><a href="" target="_blank">Privacy </a></div>
					<div class="developed"><a href="" target="_blank">Terms </a></div>
				</div><!--/ .adjective-->

			</div><!--/ .columns-->

		</div><!--/ .container -->

	</footer><!--/ #footer -->

</div><!--/ #wrapper-->





<?php echo $this->headScript()
                ->prependFile($this->basePath() . '/application/js/custom.js')
                ->prependFile($this->basePath() . '/application/js/config.js')
                ->prependFile($this->basePath() . '/application/js/jquery.touchswipe.min.js')
                ->prependFile($this->basePath() . '/application/js/fancybox/jquery.fancybox.pack.js')
                ->prependFile($this->basePath() . '/application/js/jquery.jflickrfeed.min.js')
                ->prependFile($this->basePath() . '/application/js/jquery.jcarousel.min.js')
                ->prependFile($this->basePath() . '/application/js/jquery.blackandwhite.min.js')
                ->prependFile($this->basePath() . '/application/js/jquery.cycle.all.min.js')
                ->prependFile($this->basePath() . '/application/js/layerslider/js/layerslider.kreaturamedia.jquery.js')
                ->prependFile($this->basePath() . '/application/js/layerslider/js/layerslider.transitions.js')
                ->prependFile($this->basePath() . '/application/js/layerslider/js/jquerytransit.js')
                ->prependFile($this->basePath() . '/application/js/jquery.easing.1.3.min.js')
                ->prependFile('https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js')
; ?>


</body>
</html>
