<div class="container">
	<div class="row">
		<div id="content" class="col-lg-12">





			<!-- PAGE HEADER-->
			<div class="row">
				<div class="col-sm-12">
					<div class="page-header">
						<div class="clearfix">
							<h3 class="content-title pull-left">Your Signing Sources, <a href="<?php echo $this->notaryProfileLink; ?>"><?php echo $this->notaryFirstName; ?></a></h3>
						</div>
						<div class="description">Choose a source you would like to begin with or use our Search Feature.</div>
					</div>
				</div>
			</div>
			<!-- /PAGE HEADER -->



			<!-- Section Buttons CONTENT -->
			<div class="row">
				<!-- Page Specific Buttons -->
				<span class="ntzSectionHeadingButtons pull-right">

					<a class="btn btn-primary" href="/NotarySignings" style="padding: 8px; margin-top: -5px;">
						<i class="fa fa-paperclip fa-fw"></i> Home
					</a>

					<div class="btn-group dropdown" style="margin-bottom:5px">

						<a class="btn btn-primary" href="/NotarySigningOrders" style="padding: 8px;">
							<span class="visible-xs">Orders</span>
							<span class="visible-sm">Orders</span>
							<span class="visible-md">Signing Orders</span>
							<span class="visible-lg">Signing Orders</span>
						</a>
						<button class="btn btn-primary dropdown-toggle" style="padding: 8px;" data-toggle="dropdown">
							<span class="caret"></span>
						</button>
						<ul class="dropdown-menu pull-right">
							<li><a href="#">Action</a></li>
							<li><a href="#">Another action</a></li>
							<li><a href="#">Something else here</a></li>
							<li class="divider"></li>
							<li><a href="#">Separated link</a></li>
						</ul>

					</div>

					<div class="btn-group dropdown" style="margin-bottom:5px">

						<a class="btn btn-primary" href="/NotarySigningSources"  style="padding: 8px;">
							<span class="visible-xs">Sources</span>
							<span class="visible-sm">Sources</span>
							<span class="visible-md">Signing Sources</span>
							<span class="visible-lg">Signing Sources</span>
						</a>
						<button class="btn btn-primary dropdown-toggle" style="padding: 8px;" data-toggle="dropdown">
							<span class="caret"></span>
						</button>
						<ul class="dropdown-menu pull-right">
							<li><a href="#">Action</a></li>
							<li><a href="#">Another action</a></li>
							<li><a href="#">Something else here</a></li>
							<li class="divider"></li>
							<li><a href="#">Separated link</a></li>
						</ul>

					</div>

					<div class="btn-group dropdown" style="margin-bottom:5px">

						<a class="btn btn-primary" href="/NotaryData"  style="padding: 8px;">
							<span class="visible-xs">Data</span>
							<span class="visible-sm">Data</span>
							<span class="visible-md">Data & Reports</span>
							<span class="visible-lg">View Data & Reports</span>
						</a>
						<button class="btn btn-primary dropdown-toggle" style="padding: 8px;" data-toggle="dropdown">
							<span class="caret"></span>
						</button>
						<ul class="dropdown-menu pull-right">
							<li><a href="#">Action</a></li>
							<li><a href="#">Another action</a></li>
							<li><a href="#">Something else here</a></li>
							<li class="divider"></li>
							<li><a href="#">Separated link</a></li>
						</ul>

					</div>

				</span>
				<!-- /Page Specific Buttons -->
			</div>
		   	<!-- /Section Buttons CONTENT -->


			<div class="separator"></div>

			<!-- All Signing Sources-->
			<div class="row">
				<div class="col-md-12">
					<!-- BOX -->
					<div class="box border blue">
						<div class="box-title">
							<h4><i class="fa fa-table"></i>Signing Orders</h4>
							<div class="tools hidden-xs">
								<a href="#box-config" data-toggle="modal" class="config">
									<i class="fa fa-cog"></i>
								</a>
								<a href="javascript:;" class="reload">
									<i class="fa fa-refresh"></i>
								</a>
								<a href="javascript:;" class="collapse">
									<i class="fa fa-chevron-up"></i>
								</a>
							</div>
						</div>

						<div class="box-body">
							<table id="singingSection_SigningSources_AllSigningSources" cellpadding="0" cellspacing="0" border="0" class="datatable table table-striped table-bordered table-hover">
								<thead>
									<tr>
										<th>
											<span class="visible-xs">Name</span>
											<span class="visible-sm">Src Name</span>
											<span class="visible-md">Source Name</span>
											<span class="visible-lg">Signing Source Name</span>
										</th>
										<th>
											<span class="visible-xs"># Signings</span>
											<span class="visible-sm"># Signings</span>
											<span class="visible-md">Nbr of Signings</span>
											<span class="visible-lg">Number of Signings</span>
										</th>
										<th>Rating</th>
										<th class="hidden-xs">Zip</th>

										<th class="hidden-xs">
											<span class="visible-xs pop-top" data-title="More Info" data-content="How much this signing source is likely to pay you.">Avg Fee Pd</span>
											<span class="visible-sm pop-top" data-title="More Info" data-content="How much this signing source is likely to pay you.">Avg. Fee Paid</span>
											<span class="visible-md pop-top" data-title="More Info" data-content="How much this signing source is likely to pay you.">Average Fee Paid</span>
											<span class="visible-lg pop-top" data-title="More Info" data-content="How much this signing source is likely to pay you.">Average Fee Paid</span>
										</th>
										<th class="hidden-xs">
											<span class="visible-xs pop-top" data-title="More Info" data-content="How long this signing source will typically take to pay you for a completed signing.">Avg. Pmt Delay</span>
											<span class="visible-sm pop-top" data-title="More Info" data-content="How long this signing source will typically take to pay you for a completed signing.">Avg. Payment Delay</span>
											<span class="visible-md pop-top" data-title="More Info" data-content="How long this signing source will typically take to pay you for a completed signing.">Average Payment Delay</span>
											<span class="visible-lg pop-top" data-title="More Info" data-content="How long this signing source will typically take to pay you for a completed signing.">Average Payment Delay</span>
										</th>
										<th class="hidden-xs">
											<span class="visible-xs pop-top" data-title="More Info" data-content="How likely this signing source is to actually pay you.">% Paid</span>
											<span class="visible-sm pop-top" data-title="More Info" data-content="How likely this signing source is to actually pay you.">PCT Paid</span>
											<span class="visible-md pop-top" data-title="More Info" data-content="How likely this signing source is to actually pay you.">PCT Signings Paid</span>
											<span class="visible-lg pop-top" data-title="More Info" data-content="How likely this signing source is to actually pay you.">Percentage of Signings Paid</span>
										</th>
									</tr>
								</thead>
								<tbody>
									<tr>
										<th>Source Name</th>
										<th>Number of Signings</th>
										<th>Rating</th>
										<th class="hidden-xs">Zip</th>

										<th class="hidden-xs">Average Fee Paid</th>
										<th class="hidden-xs">How long they take to pay</th>
										<th class="hidden-xs">PCT Signings Paid</th>
									</tr>
								</tbody>
								<tfoot>
									<tr>
										<th>
											<span class="visible-xs">Name</span>
											<span class="visible-sm">Src Name</span>
											<span class="visible-md">Source Name</span>
											<span class="visible-lg">Signing Source Name</span>
										</th>
										<th>
											<span class="visible-xs"># Signings</span>
											<span class="visible-sm"># Signings</span>
											<span class="visible-md">Nbr of Signings</span>
											<span class="visible-lg">Number of Signings</span>
										</th>
										<th>Rating</th>
										<th class="hidden-xs">Zip</th>

										<th class="hidden-xs">
											<span class="visible-xs pop-top" data-title="More Info" data-content="How much this signing source is likely to pay you.">Avg Fee Pd</span>
											<span class="visible-sm pop-top" data-title="More Info" data-content="How much this signing source is likely to pay you.">Avg. Fee Paid</span>
											<span class="visible-md pop-top" data-title="More Info" data-content="How much this signing source is likely to pay you.">Average Fee Paid</span>
											<span class="visible-lg pop-top" data-title="More Info" data-content="How much this signing source is likely to pay you.">Average Fee Paid</span>
										</th>
										<th class="hidden-xs">
											<span class="visible-xs pop-top" data-title="More Info" data-content="How long this signing source will typically take to pay you for a completed signing.">Avg. Pmt Delay</span>
											<span class="visible-sm pop-top" data-title="More Info" data-content="How long this signing source will typically take to pay you for a completed signing.">Avg. Payment Delay</span>
											<span class="visible-md pop-top" data-title="More Info" data-content="How long this signing source will typically take to pay you for a completed signing.">Average Payment Delay</span>
											<span class="visible-lg pop-top" data-title="More Info" data-content="How long this signing source will typically take to pay you for a completed signing.">Average Payment Delay</span>
										</th>
										<th class="hidden-xs">
											<span class="visible-xs pop-top" data-title="More Info" data-content="How likely this signing source is to actually pay you.">% Paid</span>
											<span class="visible-sm pop-top" data-title="More Info" data-content="How likely this signing source is to actually pay you.">PCT Paid</span>
											<span class="visible-md pop-top" data-title="More Info" data-content="How likely this signing source is to actually pay you.">PCT Signings Paid</span>
											<span class="visible-lg pop-top" data-title="More Info" data-content="How likely this signing source is to actually pay you.">Percentage of Signings Paid</span>
										</th>
									</tr>
								</tfoot>
							</table>
						</div>
					</div>
					<!-- /BOX -->
				</div>
			</div>
		   	<!-- /All Signing Sources -->


		 	<div class="separator"></div>

