<?php echo $this->doctype(); ?>
<html lang="en">
<head>
	<meta http-equiv="content-type" content="text/html; charset=UTF-8">
	<meta charset="utf-8">
    <?php echo $this->headTitle('Nomsterz - Member Access.')->setSeparator(' - ')->setAutoEscape(false) ?>

	<?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0, maximum-scale=1, user-scalable=no')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge,IE=9,IE=8,chrome=1')
        ->appendName('description', '')
        ->appendName('author', '')
    ?>

	<?php echo $this->headScript()
        ->prependFile('http://css3-mediaqueries-js.googlecode.com/svn/trunk/css3-mediaqueries.js'   , 'text/javascript', array('conditional' => 'lt IE 9',))
        ->prependFile('http://html5shiv.googlecode.com/svn/trunk/html5.js'                          , 'text/javascript', array('conditional' => 'lt IE 9',))
        ->prependFile($this->basePath() . '/admin/js/flot/excanvas.min.js'                           , 'text/javascript', array('conditional' => 'lt IE 9',))
    ; ?>

    <?php echo $this->headLink
                    (
                        array
                        (
                            'rel'   =>  'shortcut icon',
                            'type'  =>  'image/vnd.microsoft.icon',
                            'href'  =>  $this->basePath() . '/application/images/favicon.ico'
                        )
                    )
                    ->prependStylesheet('http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700')
                    ->prependStylesheet($this->basePath() . '/admin/css/animatecss/animate.min.css')
                    ->prependStylesheet($this->basePath() . '/admin/js/uniform/css/uniform.default.min.css')
                    ->prependStylesheet($this->basePath() . '/admin/js/bootstrap-daterangepicker/daterangepicker-bs3.css')
                    ->prependStylesheet($this->basePath() . '/admin/font-awesome/css/font-awesome.min.css')
                    ->prependStylesheet($this->basePath() . '/admin/css/cloud-admin.css')
    ?>






</head>
<body class="login">
	<!-- PAGE -->
	<section id="page">
			<!-- HEADER -->
			<header>
				<!-- NAV-BAR -->
				<div class="container">
					<div class="row">
						<div class="col-md-4 col-md-offset-4">
							<div id="logo">
								<a href="<?php echo $this->url('home'); ?>"><img src="admin/img/logo/nomsterz-logo.png" height="60" alt="logo name" /></a>
							</div>
						</div>
					</div>
				</div>
				<!--/NAV-BAR -->
			</header>
			<!--/HEADER -->
			<!-- LOGIN -->
			<section id="login" class="<?php echo ($activity == 'login' ? 'visible' : '' ); ?>">
				<div class="container">
					<div class="row">
						<div class="col-md-4 col-md-offset-4">
							<div class="login-box-plain">
								<h2 class="bigintro">Member Sign In</h2>
								<div class="divide-40"></div>
								<form role="form">
								  <div class="form-group">
									<label for="exampleInputEmail1">Email address</label>
									<i class="fa fa-envelope"></i>
									<input type="email" class="form-control" id="exampleInputEmail1" >
								  </div>
								  <div class="form-group"> 
									<label for="exampleInputPassword1">Password</label>
									<i class="fa fa-lock"></i>
									<input type="password" class="form-control" id="exampleInputPassword1" >
								  </div>
								  <div class="form-actions">
									<label class="checkbox"> <input type="checkbox" class="uniform" value=""> Remember me</label>
									<button type="submit" class="btn btn-danger">Submit</button>
								  </div>
								</form>
								<!-- SOCIAL LOGIN -->
								<div class="divide-20"></div>
								<div class="center">
									<strong>Or login using your social account</strong>
								</div>
								<div class="divide-20"></div>
								<div class="social-login center">
									<a class="btn btn-primary btn-lg">
										<i class="fa fa-facebook"></i>
									</a>
									<a class="btn btn-info btn-lg">
										<i class="fa fa-twitter"></i>
									</a>
									<a class="btn btn-danger btn-lg">
										<i class="fa fa-instagram"></i>
									</a>
								</div>
								<!-- /SOCIAL LOGIN -->
								<div class="login-helpers">
									<a href="#" onclick="swapScreen('forgot');return false;">Forgot Password?</a> <br>
									Don't have an account with us? <a href="#" onclick="swapScreen('register');return false;">Sign up now!</a>
								</div>
							</div>
						</div>
					</div>
				</div>
			</section>
			<!--/LOGIN -->
			<!-- REGISTER -->
			<section id="register" class="<?php echo ($activity == 'signup' ? 'visible' : '' ); ?>">
				<div class="container">
					<div class="row">
						<div class="col-md-4 col-md-offset-4">
							<div class="login-box-plain">
								<h2 class="bigintro">Free Sign Up</h2>
								<div class="center">
									<strong>no credit card required</strong>
								</div>
								<div class="divide-40"></div>
								<form role="form">

								  <div class="form-group">
									<label for="exampleInputEmail1">Email address</label>
									<i class="fa fa-envelope"></i>
									<input type="email" class="form-control" id="exampleInputEmail1" >
								  </div>
								  <div class="form-group"> 
									<label for="exampleInputPassword1">Password</label>
									<i class="fa fa-lock"></i>
									<input type="password" class="form-control" id="exampleInputPassword1" >
								  </div>
								  <div class="form-group"> 
									<label for="exampleInputPassword2">Repeat Password</label>
									<i class="fa fa-check-square-o"></i>
									<input type="password" class="form-control" id="exampleInputPassword2" >
								  </div>
								  <div class="form-actions">
									<label class="checkbox"> <input type="checkbox" class="uniform" value=""> I agree to the <a href="#">Terms of Service</a> and <a href="#">Privacy Policy</a></label>
									<button type="submit" class="btn btn-success">Sign Up</button>
								  </div>
								</form>
								<!-- SOCIAL REGISTER -->
								<div class="divide-20"></div>
								<div class="center">
									<strong>Or signup using your social account</strong>
								</div>
								<div class="divide-20"></div>
								<div class="social-login center">
									<a class="btn btn-primary btn-lg">
										<i class="fa fa-facebook"></i>
									</a>
									<a class="btn btn-info btn-lg">
										<i class="fa fa-twitter"></i>
									</a>
									<a class="btn btn-danger btn-lg">
										<i class="fa fa-instagram"></i>
									</a>
								</div>
								<!-- /SOCIAL REGISTER -->
								<div class="login-helpers">
									<a href="#" onclick="swapScreen('login');return false;"> Back to Login</a> <br>
								</div>
							</div>
						</div>
					</div>
				</div>
			</section>
			<!--/REGISTER -->
			<!-- FORGOT PASSWORD -->
			<section id="forgot" class="<?php echo ($activity == 'forgot' ? 'visible' : '' ); ?>">
				<div class="container">
					<div class="row">
						<div class="col-md-4 col-md-offset-4">
							<div class="login-box-plain">
								<h2 class="bigintro">Reset Password</h2>
								<div class="divide-40"></div>
								<form role="form">
								  <div class="form-group">
									<label for="exampleInputEmail1">Enter your Email address</label>
									<i class="fa fa-envelope"></i>
									<input type="email" class="form-control" id="exampleInputEmail1" >
								  </div>
								  <div class="form-actions">
									<button type="submit" class="btn btn-info">Send Me Reset Instructions</button>
								  </div>
								</form>
								<div class="login-helpers">
									<a href="#" onclick="swapScreen('login');return false;">Back to Login</a> <br>
								</div>
							</div>
						</div>
					</div>
				</div>
			</section>
			<!-- FORGOT PASSWORD -->
	</section>
	<!--/PAGE -->

    <?php echo $this->headScript()
        ->prependFile($this->basePath() . '/admin/js/script.js'                                                          , 'text/javascript', array())
        ->prependFile($this->basePath() . '/admin/js/uniform/jquery.uniform.min.js'                                      , 'text/javascript', array())
        ->prependFile($this->basePath() . '/admin/bootstrap-dist/js/bootstrap.min.js'                              , 'text/javascript', array())
        ->prependFile($this->basePath() . '/admin/js/jquery-ui-1.10.3.custom/js/jquery-ui-1.10.3.custom.min.js'    , 'text/javascript', array())
        ->prependFile($this->basePath() . '/admin/js/jquery/jquery-2.0.3.min.js'                                         , 'text/javascript', array())
    ; ?>

    <script>
		jQuery(document).ready(function() {		
			App.setPage("login");  //Set current page
			App.init(); //Initialise plugins and elements
		});
	</script>
	<script type="text/javascript">
		function swapScreen(id) {
			jQuery('.visible').removeClass('visible animated fadeInUp');
			jQuery('#'+id).addClass('visible animated fadeInUp');
		}
	</script>
	<!-- /JAVASCRIPTS -->
</body>
</html>