<section id="content">

		<div class="container">

			<div class="page-header clearfix">

				<h1>Welcome (again) to Nomsterz</h1>

			</div><!--/ .page-header-->

			<h4 class="content-title">and thank you for successfully signing up before.</h4>

			<div class="sixteen columns row">

				<p>
					Apparently, the email you used to register has already been used to create an account.
				</p>

				<p>
					<ul>
                        <li>Check your inbox for a validation message and click the link.</li>
                        <li>If you are sure you have not used this email to signup contact us at <a href="mailto:customer_service@nomsterz.com"></a>. We'll be glad to help you straighten things out.</li>
                    </ul>
				</p>

			</div>

		</div><!--/ .container-->

	</section><!--/ #content-->