<section id="content">

		<div class="container">

			<div class="page-header clearfix">

				<h1>Welcome to Nomsterz</h1>

			</div><!--/ .page-header-->

			<h2 class="content-title">And thank you for successfully signing up!</h2>
			<h3 class="content-title">
				We're happy you could join us. We promise you really amazing features at more than affordable value.
                But, first check your inbox and validate your email. Once you do that, we can get you started!
			</h3>

			<div class="sixteen columns row">

				<p>

				</p>

			</div>

		</div><!--/ .container-->

	</section><!--/ #content-->