<section id="content">

		<div class="container">

			<div class="page-header clearfix">

				<h1>You've Activated Your Nomsterz Membership</h1>

			</div><!--/ .page-header-->

			<h2 class="content-title">you can now login and start your 90 Free Trial!</h2>

			<div class="sixteen columns row">

				<p>
					<h2>During this free trial you get:</h2>
                    <ul class="list">
                        <li><h3><i class="icon-ok"></i>Unlimited access to all available features</h3></li>
                        <li><h3><i class="icon-ok"></i>Access to all Website Templates</h3></li>
                        <li><h3><i class="icon-ok"></i>Unlimited access to ratings & reviews from other Nomsterz members</h3></li>
                        <li><h3><i class="icon-ok"></i>and much more...</h3></li>
                    </ul>
				</p>

			</div>

		</div><!--/ .container-->

	</section><!--/ #content-->