whatwedo <?php echo $customer; ?>

<section id="content" class="sbl">

		<div class="container clearfix">

			<div class="page-header clearfix">

				<h1>What we Offer Your School</h1>

			</div><!--/ .page-header-->

			<section id="main" class="twelve columns">

				<div class="ajax-content">

					<ul>

						<li class="ajax-navigation-item">

							<img src="images/temp/totally.jpg" alt="" />

							<div class="clear"></div>
							<div class="divider-solid"></div>

							<h4 class="content-title">Totally Responsive & Unbelievably Clean</h4>

							<p>
								Goodnex impresses you with fully responsiveness and highly customization. It is not so easy to surprise anybody with websites
								adaptation to the most devices, but we did it in combination of very clean and flexible design. No matter what, you will get
								perfect website looking on desktop screen, smartphones - and of course any Tablet or iPad. It looks beautiful on any device!
								Goodnex is completely adapted to your touchable and mobile device: you touch – you slide, you touch you scroll, you touch – you open.
							</p>

						</li>

						<li class="ajax-navigation-item">

							<img src="images/temp/skins.jpg" alt="" />

							<div class="clear"></div>
							<div class="divider-solid"></div>

							<h4 class="content-title">Unlimited Skins</h4>

							<p>
								Sed velit tellus, posuere in diam sit amet, dignissim molestie arcu. In id iaculis est. Nunc felis velit, placerat in quam ac,
								condimentum fringilla ipsum. Donec cursus nisl vestibulum quam eleifend, vel consectetur tortor sagittis. Nulla eu nibh felis.
								Cras quis placerat est. In non dolor eleifend, aliquet nisl a, congue velit. Nullam ipsum massa, molestie sed lacinia eget,
								lacinia nec mauris. Donec non risus eu dolor accumsan varius id sed sem.
							</p>

							<p>
								Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ultricies consectetur arcu, aliquet dignissim enim tempor eget.
								Proin id nisl sed ante mattis interdum et ac massa. Sed arcu metus, iaculis eget dolor id, fermentum fringilla velit. Nulla
								porttitor vehicula felis quis tempus. In et nulla et libero volutpat tincidunt in a ligula. Quisque viverra laoreet massa sed
								convallis. Aenean urna ipsum, sodales nec mollis at, malesuada in odio. Nulla facilisi. Duis porta mi purus, at luctus est
								imperdiet quis. Fusce semper lectus in dapibus commodo. Vestibulum in rhoncus ligula. In vestibulum sed ante eu vehicula.
								Donec pharetra, lacus vitae consectetur scelerisque, enim metus dictum mauris.
							</p>

						</li>

						<li class="ajax-navigation-item">

							<h4 class="content-title">Services</h4>

							<p>
								Sed velit tellus, posuere in diam sit amet, dignissim molestie arcu. In id iaculis est. Nunc felis velit, placerat in quam ac,
								condimentum fringilla ipsum. Donec cursus nisl vestibulum quam eleifend, vel consectetur tortor sagittis. Nulla eu nibh felis.
								Cras quis placerat est. In non dolor eleifend, aliquet nisl a, congue velit. Nullam ipsum massa, molestie sed lacinia eget,
								lacinia nec mauris. Donec non risus eu dolor accumsan varius id sed sem.
							</p>

							<p>
								Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ultricies consectetur arcu, aliquet dignissim enim tempor eget.
								Proin id nisl sed ante mattis interdum et ac massa. Sed arcu metus, iaculis eget dolor id, fermentum fringilla velit. Nulla
								porttitor vehicula felis quis tempus. In et nulla et libero volutpat tincidunt in a ligula. Quisque viverra laoreet massa sed
								convallis. Aenean urna ipsum, sodales nec mollis at, malesuada in odio. Nulla facilisi. Duis porta mi purus, at luctus est
								imperdiet quis. Fusce semper lectus in dapibus commodo. Vestibulum in rhoncus ligula. In vestibulum sed ante eu vehicula.
								Donec pharetra, lacus vitae consectetur scelerisque, enim metus dictum mauris, quis pharetra est ante sed diam. Duis id
								lectus nunc. Nunc vitae vehicula purus.
							</p>

						</li>

					</ul>

				</div>

			</section><!--/ #main-->

			<aside id="sidebar" class="four columns">

				<ul class="ajax-nav">

					<li><a href="#">Totally Responsive</a></li>
					<li><a href="#">Unlimited Skins</a></li>
					<li><a href="#">Services</a></li>

				</ul><!--/ .ajax-nav-->

			</aside><!--/ #sidebar-->

		</div><!--/ .container-->

	</section> <!--/ #content-->